### ISSUE TITLE
How can i run this code?

### ISSUE THREAD

**Issue by Oblivion97** [irdanish11/Sentence-Prediction-using-LSTMs_aka-Language-Modeling#2]
can you please guide me on how I can run this code? I tried on Jupiter notebook but facing a problem. can you please help? thanks.

**Comment by irdanish11** [comment]
@Oblivion97  You will probably face problems to run this code running on a notebook, the reason is that we have multiple modules and every module is dependent on some other module. The code is formatted in a way so that either you can run it from python console or any IDE for example spyder.
The use of spyder is recommended.

**Comment by Oblivion97** [comment]
Hi, thanks for responding. I ran the code in pycharm. it's okay. one thing I'm really confused, is the preprocessing file is totally independent? I mean, I need to preprocess data first with the script then train? can you clarify? thanks.

**Comment by irdanish11** [comment]
@Oblivion97 you are more than welcome, Yes first you have to preprocess data separately, the preprocessing module saved the processed data in a text file, and then you can load that text file in the model.py module and then go along with it.

**Comment by Oblivion97** [comment]
I ran the code separately.my dataset is actually in a text file(.txt).it's showing this error,



`Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/PreProcessData/PreProcessDataset.py", line 20, in <module>
    if data['description'][i] not in unique_data:
  File "G:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "G:\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1618, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1626, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'description'`


can you help please.

**Comment by irdanish11** [comment]
The error is due to this ``` data['description'][i] ``` in my case I had the csv file which in python becomes Dataframe, so my desired data was in the `description` column. As you have text file so you should remove this and iterate over all the lines to find duplicate ones. Probably in you case the type of ``` data ``` variable would be list. So please watch out that, and before just running the code have a look at the code and try a dry run so you can understand what is happening.

**Comment by Oblivion97** [comment]
Hi again, can youo tell me what is the beam search file for?

**Comment by irdanish11** [comment]
Beam search is for generating multiple sentence suggestions

**Comment by Oblivion97** [comment]
Hi, thanks for responding.can you tell me how I can get output by giving input randomly?in your program, it generating output after the input words.like,

Input: "modus to install"
Output: "modus to install and integrate not wifi"

but is it possible to do something like,

Input: "modus install wifi"
Output: "modus to install and integrate not wifi"

can you help please?

**Comment by irdanish11** [comment]
This is model is for sentence prediction, what you are asking a mix of sentence auto correction and sentence prediction which is not possible with this model

**Comment by Sathya0425** [comment]
I am getting an error on model.py on tokenizer.fit_to_text function. Can you please help to fix this

**Comment by irdanish11** [comment]
> I am getting an error on model.py on tokenizer.fit_to_text function. Can you please help to fix this

Please provide full traceback of the error,

Furthermore, I'm adding a general guide here, first, you have to perform preprocessing on your data using the [preprocessing.py](https://github.com/irdanish11/Sentence-Prediction-using-LSTMs_aka-Language-Modeling/blob/master/preprocessing.py) file, and then train your model using [model.py](https://github.com/irdanish11/Sentence-Prediction-using-LSTMs_aka-Language-Modeling/blob/master/model.py)
For more read this [blog](https://irdanish.medium.com/sentence-prediction-using-a-word-level-lstm-text-generator-language-modeling-e48e6097a51e)
